version: 2.1

jobs:
  build:
    docker:
    - image: eu.gcr.io/sanity-cloud/go-tools
      auth: {username: "_json_key", password: "$GCR_CREDENTIALS"}
    working_directory: /build
    environment:
      GOPATH: "/build/.go"
    steps:
    - checkout
    - run:
        name: Build
        command: go build ./...
    - run:
        name: Run tests
        command: |
          mkdir -p /tmp/artifacts
          gotestsum --junitfile /tmp/artifacts/gotestsum-report.xml -- -cover -coverprofile cover.out ./...
          go tool cover -html=cover.out -o /tmp/artifacts/coverage.html
    - store_test_results:
        path: /tmp/artifacts

workflows:
  version: 2

  # Build branches and PRs.
  build-and-test:
    jobs:
    - build:
        context: [default]
